#name of the workflow 
name: hello workflow

on:
  workflow_dispatch:
  #  push:
  #  branches:
  #    - main

jobs:

  greeting:

    runs-on: ubuntu-latest

    steps:

      - name: Say hello to world
        run: echo "Hello WORLD"

      - name: say hello to user
        run: echo "Hello $USER"
  
  details:

    runs-on: ubuntu-latest
    
    steps:
      
      - name: check the python version
        run: python --version

      - name: check the docker version
        run: docker --version
