# name the this workflow is portfolio.yml

name: portfolio

on:
    push:
        branches:
            - main

jobs:

    deploy:

        runs-on: ubuntu-latest

        steps:

            - name: checkout code
              uses: actions/checkout@v4

            
            - name: Setup github pages
              uses: actions/configure-pages@v4

            - name: upload statci files
              uses: actions/upload-pages-artifact@v4


            - name: deploy to Github pages
              id: deployment
              uses: actions/deploy-pages@v4